ingredients = [
    {
        'type': 'kakao',
        'name': 'DecoMorreno',
        'calories': 303,
        'fat': 10.5,
        'carbs': 13,
        'sugar': 0.5,
        'protein': 23.5,
        'package_price': 10,
        'package_weight': 80,
    },
    {
        'type': 'platki owsiane',
        'name': 'aldi',
        'calories': 369,
        'fat': 6.8,
        'carbs': 59,
        'sugar': 1,
        'protein': 13,
        'package_price': 3,
        'package_weight': 500,
    },
    {
        'type': 'bialko',
        'name': 'allnutrition isolate white chocolate raspberry',
        'calories': 376,
        'fat': 2.9,
        'carbs': 2.6,
        'sugar': 2.5,
        'protein': 85,
        'package_price': 220,
        'package_weight': 2000,
    },
    {
        'type': 'maslo orzechowe',
        'name': 'go on',
        'calories': 603,
        'fat': 48,
        'carbs': 12,
        'sugar': 6.7,
        'protein': 27,
        'package_price': 14,
        'package_weight': 500,
    },
    {
        'type': 'jogurt',
        'name': 'piatnica skyr',
        'calories': 64,
        'fat': 0,
        'carbs': 4.1,
        'sugar': 4.1,
        'protein': 12,
        'package_price': 7.50,
        'package_weight': 450,
    },
    {
        'type': 'woda',
        'name': 'woda',
        'calories': 0,
        'fat': 0,
        'carbs': 0,
        'sugar': 0,
        'protein': 0,
        'package_price': 0,
        'package_weight': 100,
    }
]

